### PR TITLE
FIX manifest path

### PR DESCRIPTION
**Pull request by araimple**

### CODE REVIEW

**Comment by araimple** [comment]
@googlebot  I signed it!

**Review by pipe-alt — COMMENTED** [review]
Unity 2020.1 and upwards need the .androidlib part to work. if this commit is made the link between the path and the folder itself would broke too because the folder has the .androidlib part too.

I saw your [issue](https://github.com/googleads/googleads-mobile-unity/issues/1493) I'm gonna try answer it there

**Comment by stowy** [comment]
This is not required as per @pipe-alt - please remove and re-import the plugin.

**Comment by araimple** [comment]
@stowy @pipe-alt 
Thank you for comment.
when I re-import .unitypackage, then it work.

**Pull request closed without merging**
